# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.





title: Steve Moy Show
email: info@stephenmoy.com
author: Stephen Moy

# description: >- # this means to ignore newlines until "baseurl:"
#   In these episodes, I have conversations about life, 
#   relationships, and common interests
description: "On this channel, we engage in thought-provoking and candid conversations with our loved ones, friends, and interesting people about life, relationships, and personal challenges. Our podcast is a safe space where we explore and share our experiences, perspectives, and insights on various topics that affect us as individuals and as a community.  
From heartwarming stories of triumph and resilience to vulnerable discussions on mental health, our podcast aims to inspire and empower our listeners through authentic and relatable conversations. We believe that by sharing our stories and learning from each other, we can grow, heal, and build stronger relationships.  
So join us on this journey as we dive deep into the complexities of life and navigate through its ups and downs together. Whether you're looking for guidance, connection, or simply a good listen, this podcast has something for everyone."
subtitle: "Conversations about life, relationships, and personal challenges"
lang: en-us
author: Stephen Moy
# copyright: "&#xA9; 2023"

#Exclude local build settings
exclude: ['readme.md', 'Gemfile.lock', 'Gemfile']

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://stephenmoy.com/podcast" # the base hostname & protocol for your site, e.g. http://example.com
# url: "https://enlyte.github.io"
permaurl: "https://stephenmoy.com"

email: info@stephenmoy.com
twitter_username: stevemoy
instagram_username: therealstevemoy
github_username: enlyte
# Build settings
theme: minima
plugins:
  - jekyll-feed
# timezone: America/New_York

# markdown: kramdown


# permalink: /:categories/:year/:month/:day/:title:output_ext
# permalink: /:year/:title.html

#Timezone
# timezone: America/New_York
# timezone: Australia/Sydney

#Setup for Pages
# include: ['_pages']

# Build settings
# markdown: kramdown



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
